[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "build"
  command = "npm run netlify-build"

[build.environment]
  NODE_VERSION = "18"

# 以下是可选的性能优化设置
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true